// <auto-generated />
using System;
using FK3_skilaverkefni_EF_Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FK3_skilaverkefni_EF_Core.Migrations
{
    [DbContext(typeof(SchoolDBContext))]
    partial class SchoolDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FK3_skilaverkefni_EF_Core.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Groups", (string)null);
                });

            modelBuilder.Entity("FK3_skilaverkefni_EF_Core.Models.Mark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Marks", (string)null);
                });

            modelBuilder.Entity("FK3_skilaverkefni_EF_Core.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("First_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Last_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MarkId")
                        .HasColumnType("int");

                    b.HasKey("StudentId");

                    b.HasIndex("MarkId");

                    b.ToTable("Students", (string)null);
                });

            modelBuilder.Entity("FK3_skilaverkefni_EF_Core.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("MarkId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MarkId");

                    b.ToTable("Subjects", (string)null);
                });

            modelBuilder.Entity("FK3_skilaverkefni_EF_Core.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("First_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Last_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teachers", (string)null);
                });

            modelBuilder.Entity("SubjectTeacher", b =>
                {
                    b.Property<int>("SubjectsId")
                        .HasColumnType("int");

                    b.Property<int>("TeachersId")
                        .HasColumnType("int");

                    b.HasKey("SubjectsId", "TeachersId");

                    b.HasIndex("TeachersId");

                    b.ToTable("SubjectTeacher", (string)null);
                });

            modelBuilder.Entity("FK3_skilaverkefni_EF_Core.Models.Group", b =>
                {
                    b.HasOne("FK3_skilaverkefni_EF_Core.Models.Student", null)
                        .WithMany("Group_Id")
                        .HasForeignKey("StudentId");
                });

            modelBuilder.Entity("FK3_skilaverkefni_EF_Core.Models.Student", b =>
                {
                    b.HasOne("FK3_skilaverkefni_EF_Core.Models.Mark", null)
                        .WithMany("StudentId")
                        .HasForeignKey("MarkId");
                });

            modelBuilder.Entity("FK3_skilaverkefni_EF_Core.Models.Subject", b =>
                {
                    b.HasOne("FK3_skilaverkefni_EF_Core.Models.Mark", null)
                        .WithMany("Subject_id")
                        .HasForeignKey("MarkId");
                });

            modelBuilder.Entity("SubjectTeacher", b =>
                {
                    b.HasOne("FK3_skilaverkefni_EF_Core.Models.Subject", null)
                        .WithMany()
                        .HasForeignKey("SubjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FK3_skilaverkefni_EF_Core.Models.Teacher", null)
                        .WithMany()
                        .HasForeignKey("TeachersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FK3_skilaverkefni_EF_Core.Models.Mark", b =>
                {
                    b.Navigation("StudentId");

                    b.Navigation("Subject_id");
                });

            modelBuilder.Entity("FK3_skilaverkefni_EF_Core.Models.Student", b =>
                {
                    b.Navigation("Group_Id");
                });
#pragma warning restore 612, 618
        }
    }
}
